services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Порт для RabbitMQ
      - "15672:15672" # Порт для RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  teamlead-1:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: teamlead
      APP_ID: 1
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  teamlead-2:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: teamlead
      APP_ID: 2
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  teamlead-3:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: teamlead
      APP_ID: 3
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  teamlead-4:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: teamlead
      APP_ID: 4
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  teamlead-5:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: teamlead
      APP_ID: 5
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  junior-1:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: junior
      APP_ID: 6
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  junior-2:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: junior
      APP_ID: 7
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  junior-3:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: junior
      APP_ID: 8
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  junior-4:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: junior
      APP_ID: 9
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  junior-5:
    image: employee
    build:
      context: .
      dockerfile: Employee/Dockerfile
    environment:
      APP_TYPE: junior
      APP_ID: 10
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  hrdirector:
    image: hrdirector
    build:
      context: .
      dockerfile: HRDirector/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  hrmanager:
    image: hrmanager
    build:
      context: .
      dockerfile: HRManager/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy