CREATE TABLE Employee
(
    id   INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(10) NOT NULL CHECK ( role IN ('junior', 'teamlead'))
);

CREATE TABLE Hackathon
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    harmonic_mean FLOAT NOT NULL
);

CREATE TABLE Wishlist
(
    id           INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hackathon_id INT NOT NULL REFERENCES Hackathon (id),
    employee_id  INT NOT NULL REFERENCES Employee (id)
);

CREATE TABLE Team
(
    id           int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hackathon_id INT NOT NULL REFERENCES Hackathon (id),
    teamlead_id  INT NOT NULL REFERENCES Employee (id),
    junior_id    INT NOT NULL REFERENCES Employee (id)
);

CREATE TABLE WishlistEmployee
(
    wishlist_id         INT NOT NULL REFERENCES wishlist (id),
    desired_employee_id INT NOT NULL REFERENCES Employee (id),
    rank                INT NOT NULL CHECK ( rank >= 0),
    PRIMARY KEY (wishlist_id, desired_employee_id)
);